### ISSUE TITLE
Opening the ImageViewer automatically dismisses the StatusBar on Android

### ISSUE THREAD

**Issue by murad-alm** [thesmythgroup/easy_image_viewer#15]
## Describe the Issue

When the function `showImageViewer()` is called, the top Bar (Status Bar) in Android is automatically dismissed. Passing the argument `immersive` as `false` doesn't change this behaviour.

## Expected behavior
The StatusBar shouldn't be hidden after returning from the "view image" screen.

### Before opening the ImageViewer:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="https://user-images.githubusercontent.com/39278387/169296068-632fd8c3-e9dd-4b66-bb09-57ec706b3bf0.jpg" width="350" height="650">

### After opening the ImageViewer:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="https://user-images.githubusercontent.com/39278387/169295500-501ea661-c2be-4446-9591-0a13e1c48c05.jpg" width="350" height="650">

_Edit: typo_

**Comment by jfahrenkrug** [comment]
@murad-alm Thank you for this thorough bug report. We'll take a look soon.

**Comment by murad-alm** [comment]
## Solution Attempt 1:
Added this line 
`SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: SystemUiOverlay.values);`
To the `initState()` function solved this behaviour when exiting the "viewImage" Screen with the top right **x button**.
### Problem: 
When using the back button (or swipe gesture) to close the Image/screen, this issue remains.

**Comment by murad-alm** [comment]
### Strage Behaviour:
The `onViewerDismissed()` parameter/function is not being called when the dialog is closed by a back swipe or by using the back button.

**Comment by murad-alm** [comment]
## Workaround:
Setting the `immersive: flase`  and `useSafeArea: true` would keep the StatusBar visible in the dialog and after closing it.
That being said, it is a workaround and for people who don't want the StatusBar to be visible when an Image Dialog is opened (as in my case), this might not be the answer.

Most importantly, and as mentioned in https://github.com/thesmythgroup/easy_image_viewer/issues/15#issuecomment-1131670449, the `onViewerDismissed()` bug should be fixed, as a back swipe or a back button press is more natural for mobile users than seeking the **x button** in the upper right corner (IMO).

@jfahrenkrug I'm interested to hear your opinion/answer :)

**Comment by jfahrenkrug** [comment]
@murad-alm Sorry for the delay. I've put up a PR here that should fix your issue: https://github.com/thesmythgroup/easy_image_viewer/pull/19 Could you confirm that this does indeed fix things? Thanks :)
