### ISSUE TITLE
Rounded corners when useMaterial3=true

### ISSUE THREAD

**Issue by linus-ha** [thesmythgroup/easy_image_viewer#16]
## Describe the Issue

When your `MaterialApp.theme`'s `ThemeData.useMaterial3 `is set to `true` the corners in the full screen image viewer are rounded off, so that the app behind is still visible.

## Expected behavior

The whole background should be black.

## Steps to Reproduce

Set the `MaterialApp.theme`'s `ThemeData.useMaterial3 ` to `true` and `showImageViewer()`

```
import 'package:flutter/material.dart';
import 'package:easy_image_viewer/easy_image_viewer.dart';

void main() {
  runApp(MaterialApp(
    theme: ThemeData(
      useMaterial3: true, // important
    ),
    home: const MyHomePage(),
  ));
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
            onPressed: () => showImageViewer(
                  context,
                  Image.network("https://picsum.photos/200").image,
                ),
            child: const Text("click")),
      ),
    );
  }
}
```

## Other Information

![grafik](https://user-images.githubusercontent.com/30652341/170325780-4e77efec-3f41-4f81-b720-f34f198e7367.png)

**Comment by jfahrenkrug** [comment]
@linus-ha Thanks so much for this great ticket and sorry that it took me a while to get back to you. I've implemented a fix here: https://github.com/thesmythgroup/easy_image_viewer/pull/20 I'll close this ticket, but feel free to re-open if it doesn't address your issue.

**Comment by linus-ha** [comment]
Thank you very much for fixing this! Took me even longer to respond 😅. Works great!
