### ISSUE TITLE
showImageViewerPager: Open in specific page.

### ISSUE THREAD

**Issue by henry2man** [thesmythgroup/easy_image_viewer#18]
## Describe the Feature

As a developer I want to go to an specific page when `showImageViewerPager` is invoked.

I'm using the package on a chat page, so I want to show an specific picture (the tapped one) but also I want users to swipe rigth and left in order to show other chat images.

## Suggested Solution

Add an "initialPage" property to `showImageViewerPager`

## Other Information
n/a

**Comment by jfahrenkrug** [comment]
@henry2man Hey Henry, thanks for your question. This is already possible! The `imageProvider` you pass into `showImageViewerPager` has an `initialIndex` property for exactly that use case. You can see an example in the example app: https://github.com/thesmythgroup/easy_image_viewer/blob/main/example/lib/main.dart#L83

I'll close this for now, but let me know if you have issues with this. Thanks!

**Comment by henry2man** [comment]
Ok, Many thanks for the information.I didn't take notice about that.

**Comment by henry2man** [comment]
> This is already possible! The `imageProvider` you pass into `showImageViewerPager` has an `initialIndex` property for exactly that use case

It works like a charm! :)

Now I have another issue with desktop/probably web support and page changing... I'll report in a separate issue.
