### ISSUE TITLE
Double click zoom in / out

### ISSUE THREAD

**Issue by xavinuno** [thesmythgroup/easy_image_viewer#24]
## Describe the Feature

Is it possible to have feature that can make double click to zoom in and, if it zoomed can make double click to zoom out to original fit?

**Comment by jfahrenkrug** [comment]
That's a good feature request, thank you, I'll think about a solution.

**Comment by jfahrenkrug** [comment]
This is closed by https://github.com/thesmythgroup/easy_image_viewer/pull/26
