### ISSUE TITLE
[Feature request] Add loading indicator while image is being loaded

### ISSUE THREAD

**Issue by sunenvidiado-nx** [thesmythgroup/easy_image_viewer#34]
## Describe the Feature

Add a loading indicator or spinner widget while the image is being loaded.

## Suggested Solution

Maybe a `loadingIndicator` property can be added that accepts a `Widget`. This way, while the image is loading, a custom spinner widget of our choice is displayed. I think it would be awesome to have this option added.

## Other Information

n/a

**Comment by RemonYounan** [comment]
+1 for this feature request!

Adding a loading indicator or spinner widget while the image is being loaded would greatly improve the user experience. I think it would be awesome to have a loadingIndicator property that accepts a Widget. This way, developers can easily customize the spinner widget according to their design preferences.

Please consider implementing this feature as it would be a valuable addition to the package and benefit the Flutter community.

Thank you!

**Comment by jfahrenkrug** [comment]
Thank you, that sounds like a great addition. I'll try to find time for this soon.

**Comment by jfahrenkrug** [comment]
@RemonYounan @amazing-sun You can find an initial implementation here: https://github.com/thesmythgroup/easy_image_viewer/issues/34 Let me know what you think of this approach. Thanks!

**Comment by jfahrenkrug** [comment]
@RemonYounan @amazing-sun Did you have a chance to try out https://github.com/thesmythgroup/easy_image_viewer/commit/6b9cc824b2a5e86ee41b9787640324d071ce1259?

**Comment by amazing-sun** [comment]
Hello @jfahrenkrug, I've had a busy few days, but I'll definitely take a look at it when I have some free time over the weekend 🤠

**Comment by amazing-sun** [comment]
Hey @jfahrenkrug, I just checked it and using an image provider instead of a widget as an argument is a good idea. But I noticed that the loading widget doesn't appear right away.

**Comment by jfahrenkrug** [comment]
@amazing-sun Thank you very much for checking. Are you able to upload a video or gif of what you are seeing and adding some details of what your code looks like exactly? Thanks!
