### ISSUE TITLE
Adding initialIndex property to showImageViewerPager

### ISSUE THREAD

**Issue by NeroThroN** [thesmythgroup/easy_image_viewer#35]
## Describe the Feature

Adding a `initialIndex` property to `showImageViewerPager`

Todo

## Suggested Solution

Added an `initialIndex` property to the `showImageViewerPager` to specify from which index it needs to display images. This is useful for situations where we have a carousel of images and when an image is tapped the `showImageViewerPager` is called to show the selected image but we can swipe to see other ones (like previous and next ones)

## Other Information

n/a

**Comment by jfahrenkrug** [comment]
@NeroThroN Thank you for your suggestion. Fortunately this already exists: You simply set the `initialIndex` on the `EasyImageProvider` (or its subclass) that you pass to `showImageViewerPager` (see https://github.com/thesmythgroup/easy_image_viewer/blob/7ab8a2fb96ddbea1a6825b2c28e6f08698552158/lib/src/easy_image_provider.dart#L6). That should work!
