### ISSUE TITLE
ImageProvider - Future or Async

### ISSUE THREAD

**Issue by jay8anks** [thesmythgroup/easy_image_viewer#38]
This is more of an inexperience issue than an easy_image_viewer issue. But, I do see this frequently with using code like your example, where the data is pretty much static. The example worked on my first try with a simple cut and paste. I was trying to get a filename from my server and combine it with the ImageProvider to load the images from a server. 

I tried making functions that returned a List-ImageProvder>, async functions, using initState, etc.  With each of these ways, I tried Futurebuilders and various async functions.

As soon as a Future or async becomes involved, I get error after error from the MultiImageProvider.

Mind sharing how someone might go about this?

I just tried stuff like this:

String hashId = await ...

final List<ImageProvider> _imageProviders = [
    Image.network("https://picsum.photos/id/1001/4912/3264/" + hashId + ".png").image,
  ];

And putting the above in functions and trying to make them async functions, so I could be sure the filename was downloaded before the ImageProvider was returned.

Note: I came up with a hack to get my app going. What I ended up doing was getting the filename on a previous page and passing it to the page with easy_image_viewer on it. This works fine. I would be interested in how a more experienced person might go about this, though.

Also, I do think the suggesting to add a loading spinner is a good one.

I will say, outside of this, everything else was pretty easy and works as advertised.

Thanks,

**Comment by jfahrenkrug** [comment]
Hi @jay8anks,

Thanks for your question. Here's a simple demo using FutureBuilder. Hope this helps!

```
import 'package:easy_image_viewer/easy_image_viewer.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AsyncDemo(),
    );
  }
}

class AsyncDemo extends StatefulWidget {
  const AsyncDemo({Key? key}) : super(key: key);

  @override
  _AsyncDemoState createState() => _AsyncDemoState();
}

class _AsyncDemoState extends State<AsyncDemo> {

  final _pageController = PageController();

  Future<List<String>> fetchURLs() async {
    // Wait for three seconds to simulate a network fetch
    await Future.delayed(const Duration(seconds: 3));

    return [
      "https://picsum.photos/id/1001/4912/3264",
      "https://picsum.photos/id/1003/1181/1772",
      "https://picsum.photos/id/1004/4912/3264",
      "https://picsum.photos/id/1005/4912/3264"
    ];
  }

  Future<EasyImageProvider> createEasyImageProvider() async {
    final urls = await fetchURLs();
    return MultiImageProvider(urls.map((url) => NetworkImage(url)).toList());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Async Demo')),
      body: FutureBuilder<EasyImageProvider>(
        future: createEasyImageProvider(),
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            EasyImageProvider easyImageProvider = snapshot.data!;
            return Center(child: 
              SizedBox(
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.height / 2.0,
                child: EasyImageViewPager(
                    easyImageProvider: easyImageProvider,
                    pageController: _pageController),
              )
            );
          } else if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          } else {
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
    );
  }
}
```

Enjoy!

**Comment by jay8anks** [comment]
Thanks. I'm sure that will be of help to other people, too. I can tell you, putting the FutureBuilder in the body tag wasn't something I would have thought of. 

My workaround of getting the filename on the previous page and passing it to the easy_image_viewer page actually saved me A LOT of typing, I see.  :)

I have an Asp.Net background. What I keep thinking is if Flutter just had something like a void preInitState () {} that ran before the widget build and initState() processes, it sure would make life a lot easier in some circumstances.

Thanks,
