### ISSUE TITLE
Close icon is cropped on `immersive: false`

### ISSUE THREAD

**Issue by g7i** [thesmythgroup/easy_image_viewer#40]
The close button in the top right corner touches the status bar when setting `immersive: false`. It is shown fine with `immersive: true`. Either provide an option to customize it or handle this in the package itself. 
Thanks....

![Screenshot_20230930_195922](https://github.com/thesmythgroup/easy_image_viewer/assets/46393634/5fbf148f-88d6-403e-8661-0206f18a696d)

**Comment by jfahrenkrug** [comment]
@g7i Thanks for reporting this. Could you please provide some extra info: Which version of Android are you using and do you also see this on iOS? Thanks!

**Comment by jfahrenkrug** [comment]
@g7i The solution is to set `useSafeArea: true` along with `immersive: false`. That should give you the desired result. Closing this ticket. 

<img width="662" alt="Screenshot 2023-10-05 at 3 14 20 PM" src="https://github.com/thesmythgroup/easy_image_viewer/assets/16358/e7e95cc4-5e71-4254-8f29-06cec731a89d">
