### ISSUE TITLE
Breaking change in 1.3.0

### ISSUE THREAD

**Issue by wferem1** [thesmythgroup/easy_image_viewer#44]
## Describe the Issue

The constructor of `EasyImageView` now has differently named parameters, which is considered a breaking change
in version 1.2.1: 

```dart
  const EasyImageView({
    Key? key,
    required this.imageProvider,
    this.minScale = 1.0,
    this.maxScale = 5.0,
    this.doubleTapZoomable = false,
    this.onScaleChanged,
  }) : super(key: key);
```
in version 1.3.0
```dart
 const EasyImageView({
    Key? key,
    required this.imageWidget,
    this.minScale = 1.0,
    this.maxScale = 5.0,
    this.doubleTapZoomable = false,
    this.onScaleChanged,
  }) : super(key: key);
```
Todo

## Expected behavior

Rename the parameter back to the old version, or retract the current version and release it as 2.0.0

## Steps to Reproduce

n/a

## Other Information

[retract pub package](https://dart.dev/tools/pub/publishing#retract)

**Comment by jfahrenkrug** [comment]
@wferem1 Thank you for reporting this and sorry for the inconvenience. I've retracted 1.3.0 and am working on a fix. I'll post an update here.

**Comment by jfahrenkrug** [comment]
@wferem1 PR: https://github.com/thesmythgroup/easy_image_viewer/pull/45

**Comment by jfahrenkrug** [comment]
@wferem1 1.3.1 has been released (https://pub.dev/packages/easy_image_viewer), thanks again. I'm closing the ticket now.
