### ISSUE TITLE
Minimum flutter version

### ISSUE THREAD

**Issue by wferem1** [thesmythgroup/easy_image_viewer#46]
## Describe the Issue

I noticed that in the `pubspec.yaml` the minimum flutter version of this package is `1.17.0`. This was until now apparently not a problem, however flutter `3.13.0` introduced the `PopScope`, which this package uses.
In the package where i use this package, I get warnings that `PopScope` is not defined, since i'm still using flutter 3.7.

## Expected behavior

Bump the minimum flutter version to 3.13.0 in the pubspec.yaml

## Steps to Reproduce

n/a

## Other Information

n/a

**Comment by jfahrenkrug** [comment]
@wferem1 Thank you, great catch! I'll look into this as well.

**Comment by jfahrenkrug** [comment]
@wferem1 PR: https://github.com/thesmythgroup/easy_image_viewer/pull/47

**Comment by jfahrenkrug** [comment]
1.3.2 is released
