### ISSUE TITLE
Show custom error widget

### ISSUE THREAD

**Issue by manandharsudhir** [thesmythgroup/easy_image_viewer#48]
## Describe the Feature

when passing the network image 
 ```
showImageViewer(
        context,
        isFile
            ? Image.file(File(imageUrl)).image
            : Image.network(
                imageUrl,
            
              ).image,
        onViewerDismissed: onDismissed)
```
like above if the imageUrl is empty or somehow there is an network exception then currently an placeholder is being shown it would be great if we could add our custom error widget on it 

## Suggested Solution
providing an onError methon on showImageViewer would be greate

**Comment by jfahrenkrug** [comment]
@manandharsudhir Great suggestion, thank you for your ticket. I've implemented support here: https://github.com/thesmythgroup/easy_image_viewer/pull/49 Please give it a try. Thanks!
