### ISSUE TITLE
The scaling state can not slide the page, and it is hoped that the content that supports scaling can turn the page without clipping the content preview. When sliding to the content boundary, the page will be triggered by sliding again

### ISSUE THREAD

**Issue by ZenderHan** [thesmythgroup/easy_image_viewer#51]
The scaling state can not slide the page, and it is hoped that the content that supports scaling can turn the page without clipping the content preview. When sliding to the content boundary, the page will be triggered by sliding again (if _pagingEnabled can slide the page, single-finger sliding preview will appear when the scaled content will be clipped and the display will be incomplete)

**Comment by jfahrenkrug** [comment]
@ZenderHan Thank you for your ticket. I'm afraid I don't understand the issue you are reporting. 
Please do the following:
1. Use the original "Bug Report" issue template and fill out every section of it with as much detail as possible.
2. Supply a sample project or a video that clearly explains what you are describing.

Thanks so much. Without that information there's little we can do and we'll have to close the ticket.
