### ISSUE TITLE
Is it possible to round photos like ClipRRect?

### ISSUE THREAD

**Issue by Al-Krause-ex** [thesmythgroup/easy_image_viewer#55]
Hey great plugin, you rock!
Can you please tell me if I can somehow round off the image?

I'm using **EasyImageViewPager**

**Comment by jfahrenkrug** [comment]
Hi @Al-Krause-ex, thanks for the kind words.

You can fully customize the widget used to display each individual image by subclassing `EasyImageProvider`, see https://github.com/thesmythgroup/easy_image_viewer?tab=readme-ov-file#customizing-progress-indicator-and-image-widget

Notice the last paragraph:

> Finally, you can even override the imageWidgetBuilder method and completely customize the appearance of each individual image. Keep in mind that it should be an "image-like" widget since it will be treated as such: the user can pinch&zoom the returned widget etc.

This is the method you'd have to override: https://github.com/thesmythgroup/easy_image_viewer/blob/main/lib/src/easy_image_provider.dart#L21

You could basically copy the default implementation and wrap the Image widget in whatever you want to create rounded corners. Hope this helps.
