### ISSUE TITLE
Unable to scroll on Windows

### ISSUE THREAD

**Issue by tobiasht** [thesmythgroup/easy_image_viewer#6]
## Describe the Issue
I am unable to scroll to the next image on Windows. 

## Expected behavior
Work the same as in the demo gif. 

## Steps to Reproduce
n/a

## Other questions
Is it possible to add an controller to navigate to the next image with the use of a button?

Can you add a widget that does not fill the entire screen?

**Comment by jfahrenkrug** [comment]
Thanks for reporting this. Could you help me with a few questions?
1. When you say "on Windows", do you mean a Flutter Desktop (Win32 beta) or a Flutter Desktop (UWP alpha) app (https://flutter.dev/desktop)?
2. Are you using a touch screen or a mouse?
3. What version of Windows are you using?

Good questions about the controller and non-full-screen support. I'll look into that.
