### ISSUE TITLE
Custom Overlay

### ISSUE THREAD

**Issue by burhanaksendir** [thesmythgroup/easy_image_viewer#8]
I want to add current image number and total image number to the right of the screen as in the picture below. Is there a feature available for this?

![3FE4949C-294E-4640-AC29-90BBBF68249E](https://user-images.githubusercontent.com/8548639/151654994-45edc5e8-868d-4f40-8931-2d47c3a4e011.jpeg)

**Comment by jfahrenkrug** [comment]
Hi @burhanaksendir, thanks for the question. There's currently no built-in way to display such a label. However, you can embed the image viewer in your own views. Take the "embedded example" as a starting point: https://github.com/thesmythgroup/easy_image_viewer/blob/main/example/lib/embedded.dart That should let you add overlays etc. Let me know if this helps.

**Comment by burhanaksendir** [comment]
Hi @jfahrenkrug, thank you. I hadn't noticed the embedded example. Very nice, I can get what I want with this.

**Comment by jfahrenkrug** [comment]
Perfect, thanks for the reply.
