### ISSUE TITLE
custom background color

### ISSUE THREAD

**Issue by troy191990** [thesmythgroup/easy_image_viewer#9]
## Describe the Feature
The theme I am using for my app is white, and the black bacground color of this widget is quite a harsh contrast color for the eyes.
So the ability to overwrite the default color (black) background would be greatly appreciated

## Suggested Solution
Add the color as a configurable value in the constructor for the showImageViewerPager showdialog widget

**Comment by jfahrenkrug** [comment]
@troy191990 Thanks for the feedback, I'll look into it.

**Comment by jfahrenkrug** [comment]
@troy191990 Hey Brent, do you mind checking out this branch and giving it a spin to see if it addresses your issue? https://github.com/thesmythgroup/easy_image_viewer/pull/10 Thanks!

**Comment by troy191990** [comment]
branch looks good. Thanks

**Comment by jfahrenkrug** [comment]
@troy191990 This is been released in version 1.0.4: https://pub.dev/packages/easy_image_viewer
